### ISSUE TITLE
Strano hanging

### ISSUE THREAD

**Issue by sbramwell** [joelmoss/strano#1]
Mr. Moss

A. Love these UI improvements; will suggest any that occur to me in the weeks to come
B. /projects/16/jobs/42 is hanging for me for quite a bit now (20 min?)   Thx for checking it out

Thanks

**Comment by joelmoss** [comment]
Seems job #42 don't exist. Try again.

**Comment by sbramwell** [comment]
hhmm, reloaded and it 404ed; retrying

**Comment by sbramwell** [comment]
Success.  Nice 'completed' message;  better than before.   Well done Joel, thanks!
