### ISSUE TITLE
Project crash since it can't load newrelic recipes

### ISSUE THREAD

**Issue by joshdvir** [joelmoss/strano#10]
In my app I'm using newrelic_rpm gem that has a rake task but strano crash and I recive this error:

ActionView::Template::Error (cannot load such file -- new_relic/recipes):
    31:     <%- if resource.job_in_progress? -%>
    32:       <%= link_to 'JOB IN PROGRESS', [resource, resource.job_in_progress], :class => "label warning" %>
    33:     <%- else -%>
    34:       <%- if resource.cloned? && resource.repo.exists? && task = resource.cap.find_task(:deploy) %>
    35:         <%= link_to 'DEPLOY NOW...', new_project_jobs_path(resource, task.fully_qualified_name), :class => "btn success" %>
    36:       <%- end -%>
    37:     <%- end -%>
  /config/deploy.rb:3:in `load'
  app/models/project.rb:108:in`block in cap'
  app/models/project.rb:107:in `cap'
  app/views/projects/show.html.erb:34:in`_app_views_projects_show_html_erb__166938183_86818670'
  app/controllers/projects_controller.rb:13:in `show'

Of course newrelic_rpm gem is installed.

**Comment by nfm** [comment]
I have the same issue when trying to load `delayed/recipes`:

```
# config/deploy/delayed_job.rb
require 'delayed/recipes'
after "deploy:stop", "delayed_job:stop"
after "deploy:start", "delayed_job:start"
after "deploy:restart", "delayed_job:restart"
```

This causes the following error in strano:

```
LoadError in Projects#show
cannot load such file -- delayed/recipes
```

**Comment by nfm** [comment]
Hm, you can fix this issue by adding the following to the strano `Gemfile`:

```
gem 'delayed_job', :require => nil
```

Or in your case, 'newrelic_rpm'.

Can't think of a better solution. Any thoughts, @joelmoss?

**Comment by joshdvir** [comment]
That did the trick.

Thanks.

**Comment by joelmoss** [comment]
Yeah that is the only known way to resolve this right now, but I'm working on a more elegant solution.
