### ISSUE TITLE
Github login is broken

### ISSUE THREAD

**Issue by attilagyorffy** [joelmoss/strano#16]
Hi,

I am not totally sure if this is related to Strano itself (or any of its dependencies) OR Github but when trying to authenticate myself via Github I am getting a 404 error. (See http://cl.ly/3g0m3t1I0B1j0y1t3t04 - NOTE: I obviously changed the redirect parameter in the URL, however i don't even think Github gets to the authentication which after it would redirect back to my Strano host)

At this point I am not sure what happens to be the real source of the problem, any help would be appreciated.

Thank you.

**Comment by attilagyorffy** [comment]
Please ignore me, turns out that my Github application was not set up correctly and so Github gave me a slightly misleading 404 error. Sorry for the inconvenience.

**Comment by pklopping** [comment]
Hey @liquid, I'm having the same issue. Do you remember how you resolved it?

**Comment by attilagyorffy** [comment]
@4p2k: I must have done something quite silly, like not setting up my API keys correctly. Or something similar. The 404 would happen when the API key between Strano and Github do not match, meaning that Github does not understand the application that is trying to access your user's data. That results in a 404 page.

(If I want to be very picky, it should probably be a 401 Unauthorized response than a 404 Not found)

**Comment by pklopping** [comment]
@liquid Yeah, that's exactly what I was doing. I only had 2 of 3 variables set in the strano.yml file. Thanks!
