### ISSUE TITLE
Multistage and User permissions

### ISSUE THREAD

**Issue by igama** [joelmoss/strano#42]
Hey, 

Just found out about the project, looks awesome. Just one question, I have a multistage env, so fart that is working. However I wanted to set permissions, User X, N can see staging, Y, Z, can see production. 

How would you recommend solving this problem? Was wondering before jumping in to the code, what your approach would be. 

Cheers

**Comment by joelmoss** [comment]
Never had a need to do that before, but happy to accept a PR.

**Comment by igama** [comment]
ok, any suggestion on where to start?
