### ISSUE TITLE
Questions bitbucket - multistage

### ISSUE THREAD

**Issue by francescoagati** [joelmoss/strano#7]
Hi 2 questions.

Strano support othere git like bitbucket?
Is there a support for multistage enviroments?

**Comment by joelmoss** [comment]
Only Github si supported at this time, but happy to look at any pull requests that add support for other providers. 

Multistage is supported using Capistrano's built-in multistage plugin. Just configure it in your repo, and Strano will pick it up and give you the option to choose which stage you want to deploy to. 

## 

Joel Moss

# Develop with Style at http://DevelopWithStyle.com

Call me +44 7791 503309
http://twitter.com/joelmoss
AIM: joelkmoss
Skype: joelmoss.info
